### ISSUE TITLE
PyPI releases?

### ISSUE THREAD

**Issue by benbz** [matrix-org/synapse-3pid-checker#2]
It is possible I'm simply failing to find it but https://pypi.org/search/?q=synapse-3pid-checker doesn't seem to return any relevant results.

As a result I'm installing from Git: `git+https://github.com/matrix-org/synapse-3pid-checker#v1.0.0`

If I'm being a crank and missing where this is in PyPI could I be sign-posted to it. If it isn't in PyPI, would it be possible to make it available there?

**Comment by H-Shay** [comment]
It looks like it was never uploaded to PyPI, I will take care of that.

**Comment by H-Shay** [comment]
https://pypi.org/project/threepid-checker/1.0.1/
